pipeline:
  name: python
  identifier: python
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: bash
        identifier: bash
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          ls -la
                          cwd
                          python3
                          print("Ankit")
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
