pipeline:
  name: python
  identifier: python
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: bash
        identifier: bash
        description: ""
        type: Custom
        variables:
          - name: access-key-id
            type: Secret
            required: true
            description: AWS access-key Id
            value: <+input>
        spec:
          providerCredential:
            type: Aws
            spec:
              connectorRef: connectawsaccount
              region: ap-south-1
              roleArn: ""
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          pwd
                          access=<+pipeline.stages.bash.variables.access-key-id>
                          connector=<+pipeline.stages.bash.spec.execution.steps.ShellScript_1.spec.executionTarget.connectorRef>
                          echo $access
                          echo $connector
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
